### ISSUE TITLE
Project as WikiLink not working?

### ISSUE THREAD

**Issue by frvkl** [trashhalo/obsidian-todo-txt#1]
> +Project are treated at [[Project]]. You can ctrl click them.

This does not seem to work for me?

**Comment by trashhalo** [comment]
What platform are you on?

**Comment by frvkl** [comment]
Windows 10, latest version of Obsidian. When checking the html in the console, no link is generated.

**Comment by trashhalo** [comment]
How bizarre. I have a windows 10 machine, ill check it tonight.

**Comment by trashhalo** [comment]
Could you try to update the plugin and try now? Might want to reload after updating. Not sure if thats magic

**Comment by frvkl** [comment]
Yes. The Project Links are working now. Thank you for the speedy response. Keep up the good work.
