### ISSUE TITLE
[FR] treat date segment as [[ link to be interactive with daily notes

### ISSUE THREAD

**Issue by wbprime** [trashhalo/obsidian-todo-txt#3]
Created/due/completed date could be treated as note links to daily notes. 

String format of created/due/completed date in todo.txt is simply "YYYY-mm-dd", and filename format for daily note is configured in daily note plugin.  So by simply adding a config item to set the daily note filename format pattern, jump to daily note from todo.txt created/due/completed date could be implemented like '+' for projects and '@' for contexts.

**Comment by wbprime** [comment]
Any progress ?

**Comment by trashhalo** [comment]
I didn't know people were using this plugin! Ill work on this feature this weekend and if you have any other ideas please share!

**Comment by trashhalo** [comment]
`@car` is now clickable like it was a tag #car
`+car` is now clickable like it was a [[car]] link
`2017-01-02` is now clickable like it was [[2017-01-2]]

**Comment by trashhalo** [comment]
I only set this up to work in the editor view. So you need to control click those links to make them work.

**Comment by wbprime** [comment]
Test and work, great job.
